### ISSUE TITLE
Inclusion of More Models 

### ISSUE THREAD

**Issue by cuthchow** [UBC-MDS/DSCI_522_group29#29]
Based on the work done so far, I feel that our analysis would benefit from the inclusion of different ML models. I believe only utilising Ridge regression might limit our scope too much. Perhaps we can include other models (ie Random Forest Regressor) in order to compare the effectiveness of different approaches.

**Comment by AndyYang80** [comment]
I have opened a pull request to incorporate random forest modelling. Since it takes a while to optimize and fit the random forest model, I have split the fit_transform_evaluate_model.py script into two. 

**The first script will process train and test data and pickle the fitted models:**

**fit_models.py** (outputs processed test data and pickled models)
**run command:** 
python src/fit_models.py --source_data=data/processed --output_dir=results

**dependencies:** 
data/processed/train_df.csv, 
data/processed/test_df.csv

**outputs:** 
data/processed/x_test_sparse.npz
data/processed/y_test.csv
data/processed/feature_names.csv
results/tables/grid_search_ridge.csv
results/tables/grid_search_ridge.csv
results/models/rf_model.pickle
results/models/ridge_model.pickle

**The second script takes the pickled models and processed test data to generate evaluation/comparison metrics:**

**compare_models.py** (outputs processed test data and pickled models)
**run command:** 
python src/compare_models.py --source_data=data/processed --output_dir=results

**dependencies:** 
data/processed/x_test_sparse.npz
data/processed/y_test.csv
data/processed/feature_names.csv
results/models/rf_model.pickle
results/models/ridge_model.pickle

**outputs:** 
results/tables/test_scores.csv
results/tables/negative_coefficients_ridge.csv
results/tables/positive_coefficients_ridge.csv
results/tables/coefficient_comparison.csv
results/figures/predicted_vs_actual_chart.png

**Comment by lirnish** [comment]
We did include more models now. We can close this issue
